### PR TITLE
Support text-2.0

### PR DESCRIPTION
**Pull request by Bodigrim**
Tested with 
```cabal
packages: .
constraints: text >= 2.0
```

### CODE REVIEW

**Comment by Bodigrim** [comment]
`text-2.0` is finally released: https://hackage.haskell.org/package/text-2.0

**Comment by Bodigrim** [comment]
@brendanhay any chance to review this soon please? It blocks some further developments.

**Review by brendanhay — APPROVED** [review]
LGTM, apologies for the delay.

**Comment by sjakobi** [comment]
Could you make a release, @brendanhay? :)

**Comment by Bodigrim** [comment]
@brendanhay just a gentle reminder to release this please, if possible.

**Comment by sjakobi** [comment]
> Could you make a release, @brendanhay? :)

Ping @brendanhay! :)

**Comment by brendanhay** [comment]
[text-manipulate-0.3.1.0](https://hackage.haskell.org/package/text-manipulate-0.3.1.0) contains the changes

**Pull request merged**
